name: Build Windows .exe with JavaFX and Java 21

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 21 (Corretto)
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Download JavaFX SDK
      run: |
        curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_windows-x64_bin-sdk.zip
        mkdir javafx-sdk
        tar -xf javafx.zip -C javafx-sdk --strip-components=1

    - name: Create output directory
      run: mkdir output

    - name: Build native .exe with jpackage
      run: |
        jpackage ^
          --type exe ^
          --input . ^
          --dest output ^
          --name PasswordManager ^
          --main-jar your-app.jar ^
          --main-class com.yourpackage.Main ^
          --runtime-image javafx-sdk ^
          --icon your-icon.ico ^
          --java-options "--add-modules javafx.controls,javafx.fxml"

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: PasswordManager-windows
        path: output/*
