name: Build Windows EXE with JavaFX and Maven

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17 (Corretto)
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Set up Maven
      uses: apache/maven-action@v1.4.0

    - name: Build fat JAR with Maven
      run: mvn clean package

    - name: Download JavaFX SDK 17.0.6
      run: |
        curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/17.0.6/openjfx-17.0.6_windows-x64_bin-sdk.zip
        mkdir javafx-sdk
        tar -xf javafx.zip -C javafx-sdk --strip-components=1

    - name: Create output directory
      run: mkdir output

    - name: Package .exe with jpackage
      run: >
        jpackage --type exe --input target --dest output --name PasswordManager
        --main-jar PasswordManager-1.0-SNAPSHOT-jar-with-dependencies.jar
        --main-class nwes.passwordmanager.Main --runtime-image javafx-sdk
        --java-options "--add-modules javafx.controls,javafx.fxml"

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: PasswordManager-windows
        path: output/*
        compression-level: 6
