# File: .github/workflows/linux-package.yml
name: Build Linux package

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout sources
      - uses: actions/checkout@v4

      # 2) JDK 17 (contains jpackage)
      - name: Set up Temurin 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven        # change to “gradle” if you use Gradle

      # 3) build your JAR
      - name: Build runnable JAR
        run: mvn -B clean package -DskipTests

      # 4) download JavaFX SDK
      - name: Download JavaFX 17 SDK
        env:
          JFX_VERSION: 17.0.15
        run: |
          curl -L -o javafx.zip \
               https://download2.gluonhq.com/openjfx/${JFX_VERSION}/openjfx-${JFX_VERSION}_linux-x64_bin-sdk.zip
          unzip -q javafx.zip
          echo "JAVAFX_SDK=$PWD/javafx-sdk-${JFX_VERSION}" >>"$GITHUB_ENV"

      # 5) package everything with jpackage
      - name: Create self-contained image with jpackage
        run: |
          # find the freshly built jar
          JAR_PATH=$(find target -maxdepth 1 -type f -name '*.jar' ! -name '*sources.jar' | head -n1)
          [ -n "$JAR_PATH" ] || { echo "No JAR found in target/"; exit 1; }
          JAR_FILE=$(basename "$JAR_PATH")

          # stage inputs
          mkdir -p dist/input
          cp "$JAR_PATH"              dist/input/
          cp "$JAVAFX_SDK"/lib/*.jar  dist/input/

          # run jpackage
          jpackage \
